package com.elmakers.mine.bukkit.plugins.persistence.data;

/**
 * Represents a single field in a data row.
 * 
 * @author NathanWolf
 *
 */
public class DataField
{
	public DataField()
	{	
	}
	
	public DataField(String name, DataType type)
	{
		this.name = name;
		this.type = type;
	}
	
	public DataField(String name, DataType type, Object value)
	{
		this.name = name;
		this.type = type;
		this.value = value;
	}
	
	public void setType(DataType type)
	{
		this.type = type;
	}

	public DataType getType()
	{
		return type;
	}
	
	public void setValue(Object value)
	{
		this.value = value;
		if (type == null)
		{
			type = DataType.getTypeFromClass(value.getClass());
		}
	}
	
	public Object getValue()
	{
		return value;
	}
	
	public void setName(String name)
	{
		this.name = name;
	}

	public String getName()
	{
		return name;
	}

	public void setAutogenerated(boolean autogenerate)
	{
		this.autogenerate = autogenerate;
	}
	
	public boolean isAutogenerated()
	{
		return autogenerate;
	}

	public void setIdField(boolean id)
	{
		idField = id;
	}
	public boolean isIdField()
	{
		return idField;
	}

	private DataType 	type;
	private Object		value;
	private String		name;
	private boolean		autogenerate;
	private boolean		idField;
}
