name: Persistence
main: com.elmakers.mine.bukkit.plugins.persistence.PersistencePlugin
version: 0.61
website: http://mine.elmakers.com
author: NathanWolf
description : A generalized persistence engine for Bukkit.
commands:
  persist:
    description: Access persistence commands
    usage: Use "phelp" for help
  phelp:
    description: Provide detailed help for any Persistence-enabled plugins
    usage: Get help on plugin commands
  su:
    description: Toggle SuperUser status (ops-only)
    usage: Use "phelp" for help
  grant:
    description: Grant players and groups access
    usage: Use "phelp" for help
  group:
    description: Manage groups
    usage: Use "phelp" for help
  deny:
    description: Deny players and groups access
    usage: Use "phelp" for help
permissions:
  Persistence:
    description: Persistence permissions
    type: map
    map:
      commands:
        description: Internal Persistence console commands
        type: map
        map:
          persist:
            description: Can manage persistence
            type: map
            map:
              save:
                description: Can save data
                type: boolean
                default: false
              list:
                description: Can list entities and schemas
                type: boolean
                default: false
              describe:
                description: Can describe entities and schemas
                type: boolean
                default: false
              reload:
                description: Can reload data
                type: boolean
                default: false
              reset:
                description: Can reset data
                type: boolean
                default: false
          phelp:
            description: If true, they can use the help command
            type: boolean
            default: true
          su:
            description: Whether a user has SU access
            type: boolean
            default: false
          group:
            description: May manage groups
            type: map
            map:
              create:
                description: May create groups
                type: boolean
                default: false
              add:
                description: May add players to groups
                type: boolean
                default: false
              remove:
                description: May remove players from groups
                type: boolean
                default: false
          grant:
            description: May grant permissions
            type: map
            map:
              player:
                description: May grant permissions to players
                type: boolean
                default: false
              group:
                description: May grant permissions to groups
                type: boolean
                default: false
          deny:
            description: May deny permissions
            type: map
            map:
              player:
                description: May deny permissions to players
                type: boolean
                default: false
              group:
                description: May deny permissions to groups
                type: boolean
                default: false