package com.elmakers.mine.bukkit.plugins.persistence.core;

import java.lang.reflect.Field;
import java.lang.reflect.InvocationTargetException;
import java.lang.reflect.Method;
import java.util.logging.Logger;

import com.elmakers.mine.bukkit.plugins.persistence.PersistencePlugin;
import com.elmakers.mine.bukkit.plugins.persistence.annotation.PersistField;
import com.elmakers.mine.bukkit.plugins.persistence.data.DataField;
import com.elmakers.mine.bukkit.plugins.persistence.data.DataRow;
import com.elmakers.mine.bukkit.plugins.persistence.data.DataTable;
import com.elmakers.mine.bukkit.plugins.persistence.data.DataType;

public class PersistedField
{
	protected PersistedField(PersistField fieldInfo, Method getter, Method setter)
	{
		this.name = getNameFromMethod(getter);
		this.getter = getter;
		this.setter = setter;
		this.field = null;
		this.fieldInfo = fieldInfo;
	}
	
	protected PersistedField(PersistField fieldInfo, Field field)
	{
		this.name = field.getName();
		this.field = field;
		this.getter = null;
		this.setter = null;
		this.fieldInfo = fieldInfo;
	}
	
	public Class<?> getType()
	{
		if (getter != null)
		{
			return getter.getReturnType();
		}
		if (field != null)
		{
			return field.getType();
		}
		return null;
	}
	
	public String getName()
	{
		return name;
	}

	public String getDataName()
	{
		if (container != null)
		{
			return getContainedName(container.getDataName(), name);
		}
		
		if (fieldInfo.name().length() > 0) return fieldInfo.name();
			
		return name;
	}
	
	public boolean set(Object o, Object value)
	{
		if (setter == null)
		{
			if (isReadOnly())
			{
				log.warning("Persistence: attempt to set() on read-only field " + getName());
			}
			return false;
		}
		if (setter != null)
		{
			try
			{
				setter.invoke(o, value);
			}
			catch(InvocationTargetException e)
			{
				return false;
			}
			catch(IllegalAccessException e)
			{
				return false;
			}
		}
		
		if (field != null)
		{
			try
			{
				field.set(o, value);
			}
			catch(IllegalAccessException e)
			{
				return false;
			}
		}
		return true;
	}
	
	public Object get(Object o)
	{
		Object result = null;
		if (getter != null)
		{
			try
			{
				result = getter.invoke(o);
			}
			catch(InvocationTargetException e)
			{
				result = null;
			}
			catch(IllegalAccessException e)
			{
				result = null;
			}
		}
		
		if (result == null && field != null)
		{
			try
			{
				result = field.get(o);
			}
			catch(IllegalAccessException e)
			{
				result = null;
			}
		}
		
		return result;
	}
	
	public void populateHeader(DataTable dataTable, PersistedField container)
	{
		DataRow headerRow = dataTable.getHeader();
		DataField field = new DataField(getDataName(), getDataType());
		field.setIdField(isIdField());
		field.setAutogenerated(isAutogenerated());
		headerRow.add(field);
		if (isIdField())
		{
			dataTable.addIdFieldName(getName());
		}
	}
	
	public void populateHeader(DataTable dataTable)
	{
		populateHeader(dataTable, null);
	}
		
	public static String getContainedName(String container, String contained)
	{
		String remainingContained = "";
		if (contained.length() > 1)
		{
			remainingContained = contained.substring(1);
		}
		
		// De plural-ize
		container = dePluralize(container);
		contained = container + contained.substring(0, 1).toUpperCase() + remainingContained;
		
		// Also de-pluralize results
		if (contained.length() > 1 && contained.charAt(contained.length() - 1) == 's')
		{
			contained = contained.substring(0, contained.length() - 1);
		}
		return dePluralize(contained);
	}
	
	public void save(DataRow row, Object o)
	{
		Object data = null;
		if (o != null)
		{
			data = get(o);
		}
		DataField field = new DataField(getDataName(), getDataType(), data);
		row.add(field);
	}
	
	public void load(DataRow row, Object o)
	{
		DataField dataField = row.get(getDataName());
		Object value = dataField.getValue();
		DataType dataType = getDataType();
		DataType valueType = dataField.getType();
		if (dataType != valueType)
		{
			value = DataType.convertTo(value, dataType);
		}
		set(o, value);
	}
	
	public DataType getDataType()
	{
		Class<?> fieldType = getType();
		return DataType.getTypeFromClass(fieldType);
	}
	
	protected static PersistedField tryCreate(PersistField fieldInfo, Field field, PersistedClass owningClass)
	{
		DataType dataType = DataType.getTypeFromClass(field.getType());
		PersistedField pField = null;

		if (dataType == DataType.OBJECT)
		{
			pField = new PersistedReference(fieldInfo, field);
		}
		else if (dataType != DataType.NULL)
		{
			pField = new PersistedField(fieldInfo, field);
		}
		else if (dataType == DataType.LIST)
		{
			pField = new PersistedList(fieldInfo, field, owningClass);
		}
		
		return pField;
	}
	
	protected static PersistedField tryCreate(PersistField fieldInfo, Method getterOrSetter, PersistedClass owningClass)
	{
		Method setter = null;
		Method getter = null;
		String fieldName = getNameFromMethod(getterOrSetter);
		Class<? extends Object> persistClass = owningClass.getType();
		
		if (fieldName.length() == 0)
		{
			return null;
		}
		
		if (isSetter(getterOrSetter))
		{
			setter = getterOrSetter;
			getter = findGetter(setter, persistClass);
		}
		else if (isGetter(getterOrSetter))
		{
			getter = getterOrSetter;
			setter = findSetter(getter, persistClass);
		}
		
		if (getter == null)
		{
			return null;
		}
		
		if (setter == null && !fieldInfo.readonly())
		{
			return null;
		}
		
		PersistedField pField = null;
		DataType dataType = DataType.getTypeFromClass(getter.getReturnType());
		
		if (dataType == DataType.OBJECT)
		{
			pField = new PersistedReference(fieldInfo, getter, setter);
		}
		else if (dataType == DataType.LIST)
		{
			pField = new PersistedList(fieldInfo, getter, setter, owningClass);
		}
		else if (dataType != DataType.NULL)
		{
			pField = new PersistedField(fieldInfo, getter, setter);
		}

		return pField;
	}

	protected static String dePluralize(String plural)
	{
		// Special cases- kinda hacky, but makes for clean schemas.
		if (plural.equals("children")) return "child";
		if (plural.equals("Children")) return "Child";
				
		if (plural.length() > 1 && plural.charAt(plural.length() - 1) == 's')
		{
			plural = plural.substring(0, plural.length() - 1);
		}
		
		return plural;
	}
	
	protected static boolean isGetter(Method method)
	{
		String methodName = method.getName();
		boolean hasGet = methodName.substring(0, 3).equals("get");
		boolean hasIs = methodName.substring(0, 2).equals("is");
		
		return hasIs || hasGet;
	}
	
	protected static boolean isSetter(Method method)
	{
		String methodName = method.getName();
		return methodName.substring(0, 3).equals("set");
	}

	protected static String getNameFromMethod(Method method)
	{
		String methodName = method.getName();
		String fieldName = "";
		if (methodName.substring(0, 2).equals("is"))
		{
			fieldName = methodName.substring(2);
		}
		else
		{
			fieldName = methodName.substring(3);
		}
		if (fieldName.length() > 0)
		{
			String fieldEnd = "";
			if (fieldName.length() > 1)
			{
				fieldEnd = fieldName.substring(1);
			}
			fieldName += fieldName.substring(0, 1).toLowerCase() + fieldEnd;
		}
		
		return fieldName;
	}

	protected static Field findField(String fieldName, Class<? extends Object> c)
	{
		Field field = null;
		
		try
		{
			c.getField(fieldName);
		}
		catch (SecurityException e)
		{
			// log.warning("Persistence: Can't access field " + fieldName + " of class " + c.getName());
		}
		catch (NoSuchFieldException e)
		{
			// log.warning("Persistence: Can't find field " + fieldName + " of class " + c.getName());
		}
		
		return field;
	}
	
	protected static Method findGetter(String fieldName, Class<? extends Object> c)
	{
		Method getter = null;
		try
		{
			getter = c.getDeclaredMethod(getGetterName(fieldName));
			if (getter != null) return getter;
		}
		catch (NoSuchMethodException e)
		{
			// log.warning("Persistence: Can't find method " + fieldName + " of class " + c.getName());
		}
		try
		{
			getter = c.getDeclaredMethod(getIsName(fieldName));
			if (getter != null) return getter;
		}
		catch (NoSuchMethodException e)
		{
			// log.warning("Persistence: Can't find method " + fieldName + " of class " + c.getName());
		}
		return null;
	}
	
	protected static Method findSetter(String fieldName, Class<? extends Object> c)
	{
		Method setter = null;
		try
		{
			setter = c.getDeclaredMethod(getGetterName(fieldName));
			if (setter != null) return setter;
		}
		catch (NoSuchMethodException e)
		{
			// log.warning("Persistence: Can't find method " + fieldName + " of class " + c.getName());
		}
		return null;
	}
	
	protected static String getSetterName(String fieldName)
	{
		return "set" + convertFieldName(fieldName);
	}

	protected static String getGetterName(String fieldName)
	{
		return "get" + convertFieldName(fieldName);
	}

	protected static String getIsName(String fieldName)
	{
		return "is" + convertFieldName(fieldName);
	}
	
	protected static String convertFieldName(String fieldName)
	{
		if (fieldName.length() > 0)
		{
			String fieldEnd = "";
			if (fieldName.length() > 1)
			{
				fieldEnd = fieldName.substring(1);
			}
			fieldName += fieldName.substring(0, 1).toLowerCase() + fieldEnd;
		}
		return fieldName;
	}
	
	protected static Method findSetter(Method getter, Class<? extends Object> c)
	{
		Method setter = null;
		String fieldName = getNameFromMethod(getter);
		String methodName = "set" + fieldName;
		try
		{
			setter = c.getMethod(methodName, getter.getReturnType());
		}
		catch (NoSuchMethodException e)
		{
			setter = null;
		}
		return setter;
	}
	
	protected static Method findGetter(Method setter, Class<?> c)
	{
		Method getter = null;
		String name = "g" + setter.getName().substring(1);
		try
		{
			getter = c.getMethod(name);
		}
		catch (NoSuchMethodException e)
		{
			getter = null;
		}
		if (getter == null)
		{
			name = "is" + setter.getName().substring(3);
			try
			{
				getter = c.getMethod(name);
			}
			catch (NoSuchMethodException e)
			{
				getter = null;
			}
		}
		return getter;
	}
	
	public void bind()
	{
		
	}
	
	public void setContainer(PersistedField container)
	{
		this.container = container;
	}
	
	public boolean isContained()
	{
		return fieldInfo.contained();
	}
	
	public boolean isAutogenerated()
	{
		return fieldInfo.auto();
	}

	public boolean isIdField()
	{
		return fieldInfo.id();
	}

	public boolean isReadOnly()
	{
		return fieldInfo.readonly();
	}

	protected PersistedField	container		= null;
	protected Method			getter			= null;
	protected Method			setter			= null;
	protected Field				field			= null;
	protected String			name			= null;
	protected PersistField		fieldInfo		= null;
	
	protected static Logger	log				= PersistencePlugin.getLogger();
}
