name: Persistence
main: com.elmakers.mine.bukkit.plugins.persistence.PersistencePlugin
version: 0.27
website: http://mine.elmakers.com
author: NathanWolf
description : A generalized persistence engine for Bukkit.
commands:
  persist:
    description: Access persistence commands
    usage: Use "phelp persist" for help
  phelp:
    description: Provide detailed help for any Persistence-enabled plugins
    usage: Use "phelp" for help
  su:
    description: Toggle SuperUser status (ops-only)
    usage: Use "phelp" for help